# Change these first
owner: lyw # Your GitHub organization or username, where this repository lives
repo: mc-uptime # The name of this repository

sites:
  - name: Online
    url: https://online.yunshanmeicai.com/
  - name: SSO
    url: https://sso.yunshanmeicai.com/
  - name: Passport
    url: https://passport.yunshanmeicai.com/
  - name: Kefu
    url: https://kf.yunshanmeicai.com/
  - name: China Telecom
    url: 106.39.250.160
    port: 443
    check: "tcp-ping"
  - name: China Unicom
    url: 114.255.145.160
    port: 443
    check: "tcp-ping"
  - name: China Mobile
    url: 223.72.140.32
    port: 443
    check: "tcp-ping"
  - name: BGP
    url: 45.254.9.48
    port: 443
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.woroot.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.meicai.cn/img/logo.9210b6eb.jpg
  name: Mc运行状态
  introTitle: "Mc运行状态"
  introMessage: 
  navbar:
    - title: Status
      href: /
    #- title: 美菜网站运行状态
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
