# Change these first
owner: windy222 # Your GitHub organization or username, where this repository lives
repo: mc-uptime # The name of this repository

sites:
  - name: Online
    url: https://online.yunshanmeicai.com/
  - name: SSO
    url: https://sso.yunshanmeicai.com/#/
  - name: dpvs-apisix-443-ct
    url: 106.120.180.248
    port: 443
    check: "tcp-ping"
  - name: dpvs-apisix-443-cu
    url: 123.125.250.100
    port: 443
    check: "tcp-ping"
  - name: dpvs-apisix-443-cm
    url: 223.71.182.8
    port: 443
    check: "tcp-ping"
  - name: dpvs-apisix-443-bgp
    url: 211.151.2.136
    port: 443
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.woroot.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.meicai.cn/img/logo.9210b6eb.jpg
  name: Meicai Uptime
  introTitle: "Meicai Urls Status"
  introMessage: Meicai Urls Status
  navbar:
    - title: Status
      href: /
    - title: Meicai Uptime
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
